---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: arc-k8s-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
     containers:
      - name: demoapp
        image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
